### ISSUE TITLE
初期値のパラメータを省略する場合のマップデータ出力の問題

### ISSUE THREAD

**Issue by bikkuri7** [urotaichi/Side#1]
初期値のパラメータを省略する設定にした場合，マップデータ(背景レイヤーのマップデータも含む)の出力に不備が発生することがあります。
例えば，マップの"map0-0"にあたる部分に何も設置せず，"map1-0"や"map2-0"にあたる部分に何か設置した場合，
"map1-0"や"map2-0"のマップデータが出力されません。

**Comment by urotaichi** [comment]
バグ報告ありがとうございます。
概要個所を修正し、issueをクローズさせていただきました。
