### ISSUE TITLE
「領域塗り潰し」の範囲が広すぎるとSideが落ちる

### ISSUE THREAD

**Issue by bikkuri7** [urotaichi/Side#3]
「領域塗り潰し」を実行するとき，一度に塗り潰す範囲が広すぎると高確率でSideが落ちます。
以下が落ちた時のレポートです。StackOverflowExceptionで落ちているようです。
![無題](https://user-images.githubusercontent.com/3896058/88404779-4ff97f00-ce09-11ea-872e-bc00646352da.png)

**Comment by urotaichi** [comment]
https://github.com/urotaichi/Side/blob/37b0c876f4d328682c848b5099cb357db3eeaba8/side/GUIDesigner.cs#L2503-L2533
再帰呼び出しが原因ぽいです
